"""add user password management fields

Revision ID: 19cdd521801c
Revises: 93be3701eeb8
Create Date: 2026-09-03 23:52:42.351198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cdd521801c'
down_revision: Union[str, None] = '9ee8bcb6944f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('invited_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'invited_at')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
