"""add_users_is_archive

Revision ID: 5d0143e0c08e
Revises: 06787f1427cf
Create Date: 2026-09-24 09:56:35.487000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0143e0c08e'
down_revision: Union[str, None] = '06787f1427cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_archive', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_archive')
    # ### end Alembic commands ###
