"""Add ondelete cascade and set null to department foreign keys

Revision ID: 90c4ef8de2e0
Revises: 4b6cb8930ec8
Create Date: 2026-08-30 16:33:27.484318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c4ef8de2e0'
down_revision: Union[str, None] = '4b6cb8930ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('is_internal_note', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('routing_rules_department_id_fkey'), 'routing_rules', type_='foreignkey')
    op.create_foreign_key(None, 'routing_rules', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tickets_department_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_department_id_fkey'), 'tickets', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'routing_rules', type_='foreignkey')
    op.create_foreign_key(op.f('routing_rules_department_id_fkey'), 'routing_rules', 'departments', ['department_id'], ['id'])
    op.drop_column('replies', 'is_internal_note')
    # ### end Alembic commands ###
