"""Adding new ticket status

Revision ID: 93be3701eeb8
Revises: 9ee8bcb6944f
Create Date: 2026-08-31 13:55:58.738013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93be3701eeb8'
down_revision: Union[str, None] = '9ee8bcb6944f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ticket_status ADD VALUE 'unresolved'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
